---
title: "economia naranja"
output: html_document
---
```{r}
orangeEconomy <- read.csv("/Users/bmonsalves/Desktop/orange_economy.csv")
data(orangeEconomy)
summary(orangeEconomy)
```

```{r}
pairs(orangeEconomy[,6:10])
```

```{r}
library(ggplot2)
```

```{r}
ggplot() +
geom_histogram(data=orangeEconomy,
               aes(x=Internet.penetration...population),
               fill="red",
               color="yellow",
               binwidth=5
               ) + 
labs(x="Penetración internet poblacion (%)",
     y="Cantidad de paises",
     title="penetración internet en paises latam") +
theme(legend.position = "none") +
theme(panel.background = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank())

```

```{r}
library(dplyr)
```

```{r}
meanEconomy <- mean(orangeEconomy$GDP.PC)
orangeEconomy <- orangeEconomy %>% mutate(strong_economy = ifelse(GDP.PC < meanEconomy,
                                                                  "Por debajo del pib per capita promedio",
                                                                  "Igual o sobre el pib per capita promedio"))
```

```{r}
ggplot(orangeEconomy,
       aes(x=strong_economy,
           y=Creat.Ind...GDP,
           fill=strong_economy)) +
geom_boxplot(alpha=0.4) + 
labs(x="Tipo de pais",
     y="Aporte economia naranja al pib",
     title="Aporte economia naranja al pib en paises latam con alto y bajo pib per capita") +
theme(legend.position = "none") +
theme(panel.background = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank())

```

```{r}
library(RColorBrewer)
```

```{r}
scaleColors = brewer.pal(9,"Reds")

topEconomiaNaranja <- orangeEconomy %>% 
  filter(GDP.PC > meanEconomy)

ggplot(topEconomiaNaranja,
       aes(x=Internet.penetration...population,
           y=GDP.PC,
           fill=Creat.Ind...GDP)) +
geom_tile() +
facet_wrap(~Country) +
scale_fill_gradientn(colors=scaleColors)
```




